### PR TITLE
#181 - Fix background-image url regexp

### PR DESCRIPTION
**Pull request by vitaliy-bobrov**
Related to issue #181

### CODE REVIEW

**Comment by almothafar** [comment]
@chrisben I want to ask when you plan to release the new version with the latest fixes?

**Comment by chrisben** [comment]
I'll do it over the week end!

**Comment by almothafar** [comment]
@chrisben good news, thanks

**Comment by chrisben** [comment]
1.1.0 is out!

**Comment by almothafar** [comment]
Hi @chrisben , thank you, but still can't install it with npm until now, it sees only version 1.0.0.

**Comment by chrisben** [comment]
I'm not the owner of that npm registry, @chaddjohnson will have to update it.
In the meantime you can use the registry "@chrisben/imgcache.js"

**Comment by chaddjohnson** [comment]
Hi @almothafar, please try now. I published 1.1.0 to NPM.

If that doesn't work, try referencing version 1.1.1. I had to bump to 1.1.1 because NPM was being dumb and thought 1.1.0 was already published to NPM (it wasn't).

If you notice any problems, let me know.

**Comment by almothafar** [comment]
Hello @chaddjohnson thank you, I was able to install version 1.1.1, it is worked.

**Pull request merged**
